# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Explore-BR' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Explore-BR

pod 'FloatingPanel', '~> 2.4'

pod 'FirebaseCore', '~> 8.9'

pod 'FirebaseAuth', '~> 8.9'

pod 'GoogleSignIn'

pod 'FirebaseFirestore', '~> 8.9'

pod 'FirebaseAnalytics', '~> 8.9'

pod 'FirebaseStorage', '~> 8.9'

pod 'FirebaseFirestoreSwift', '8.9.0-beta'

end
